custom:
  file: ${file(../config-common.yaml)}
  config:
    webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    excludeFiles: ./_para/*
# -------------------------------------------------------

    app: user-authentication
    service: simple-apps
    memorySize: 256
    timeout: 5


functions:
  handleReturnUserRegisterRequest:
    handler: handler.handleReturnUserRegisterRequest
    events:
      - http:
          path: ${self:custom.file.endpoints.${self:service}.${self:app}.register}
          method: post
          cors: true
  handleReturnUserVerifyRequest:
    handler: handler.handleReturnUserVerifyRequest
    events:
      - http:
          path: ${self:custom.file.endpoints.${self:service}.${self:app}.verify}
          method: post
          cors: true
  handleReturnUserLoginRequest:
    handler: handler.handleReturnUserLoginRequest
    events:
      - http:
          path: ${self:custom.file.endpoints.${self:service}.${self:app}.login}
          method: post
          cors: true

# -------------------------------------------------------

frameworkVersion: ${self:custom.file.custom.config.frameworkVersion}
app: ${self:custom.config.app}
service: ${self:custom.config.service}
provider:
  name: ${self:custom.file.provider.name}
  runtime: ${self:custom.file.provider.runtime}
  stage: ${self:custom.file.custom.config.stage}
  region: us-east-1
  profile: ${self:custom.file.provider.profile}
  iam:
    role: ${self:custom.file.provider.iam.role}
  memorySize: ${self:custom.config.memorySize}
  timeout: ${self:custom.config.timeout}
  deploymentBucket:
    name: abt-jbkr-test-${self:provider.stage}-lambdas
  environment:
    NODE_PATH: "./:/opt/node_modules"
    stage: ${self:provider.stage}
    jwtSecret: ${self:custom.file.jwtSecret}
package:
  individually: true
plugins:
  - serverless-webpack
