@baseURI = https://tigq10pvb0.execute-api.us-east-1.amazonaws.com/prod/simple-apps/user-authentication


#########
# Test simple apps user register
POST {{baseURI}}/register

{
    "appID": "abc123",
    "username": "hi2@jbkr.me",
    "password": "password"
}

#########
# Test simple apps user login
POST {{baseURI}}/login

{
    "appID": "abc123",
    "username": "hi2@jbkr.me",
    "password": "password"
}

#########
# Test simple apps user verify
POST {{baseURI}}/verify

{
    "appID": "abc123",
    "username": "hi2@jbkr.me",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhpMkBqYmtyLm1lIiwibmFtZSI6IkphbWVzIEJha2VyIiwiaWF0IjoxNjY4ODgzMDk3LCJleHAiOjE2Njg4ODY2OTd9.GKQipdOJH4fSz0ii43NwjubkhTFjv1GeQe4Z705Jjx0"
}
