@baseURI = https://gdm3dzyyac.execute-api.us-east-1.amazonaws.com/prod/simple-apps/user-authentication


#########
# Test simple apps user register
POST {{baseURI}}/register

{
    "appID": "1",
    "username": "hi@jbkr.me",
    "password": "password"
}

#########
# Test simple apps user login
POST {{baseURI}}/login

{
    "appID": "2",
    "username": "hi@jbkr.me",
    "password": "password"
}

#########
# Test simple apps user verify
POST {{baseURI}}/verify

{
    "appID": "1",
    "username": "hi@jbkr.me",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJRCI6IjEiLCJ1c2VybmFtZSI6ImhpQGpia3IubWUiLCJpYXQiOjE2NjkwNDM3MjUsImV4cCI6MTY2OTA0NzMyNX0.Ap3MubXvIi-6cdswgQURjRQNkR36zwiSzUR5Ap0d9qg"
}
